# Generated by Django 3.2.4 on 2021-06-27 19:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('location', models.JSONField()),
                ('is_closed', models.BooleanField(default=True)),
                ('categories', models.JSONField(blank=True)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('rating', models.IntegerField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=1000)),
                ('yelp_id', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('coffeeshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coffeeshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
