# Generated by Django 3.2.4 on 2021-06-27 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='categories',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='phone',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteshop',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
